CREATE DATABASE ITS131L_FINALS;
USE ITS131L_FINALS;

CREATE VIEW WAYBILL AS SELECT
	   CUSTOMER.USERNAME_CUSTOMER,
       CUSTOMER.RECEIVER_NAME,
       CUSTOMER.PHONE_NUMBER,
       CUSTOMER.DELIVERY_ADDRESS,
       CUSTOMER.TOWN,
       CUSTOMER.DISTRICT,
       CUSTOMER.PROVINCE,
       CUSTOMER.REGION,
       CUSTOMER.COUNTRY,
       CUSTOMER.ZIP_CODE,
       ORDERS.TRACKING_NUMBER,
       ORDERS.SHIPPING_OPTION,
       ORDERS.SHIPMENT_METHOD,
       ORDERS.EST_SHIPOUT_DATE,
       ORDERS.SHIP_TIME,
       ORDERS.ORDER_PAID_TIME,
       ORDERS.BUYER_PAID_SHIPFEE,
       ORDERS.EST_SHIPPING_FEE
       FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.USERNAME_CUSTOMER = ORDERS.USERNAME_CUSTOMER;
       
SELECT * FROM WAYBILL;
DROP VIEW WAYBILL;