CREATE DATABASE ITS131L_FINALS;
USE ITS131L_FINALS;


DELIMITER ;;
CREATE PROCEDURE TOTAL_UNITS_SOLD_PER_PRODUCT()
       BEGIN
			SELECT ORDER_PRODUCT.PRODUCT_ID, ORDER_PRODUCT.PRODUCT_NAME, SUM(ORDER_PRODUCT.QUANTITY) FROM ORDER_PRODUCT;
		END;;
	
CALL TOTAL_UNITS_SOLD_PER_PRODUCT();
DROP PROCEDURE TOTAL_UNITS_SOLD_PER_PRODUCT;